# Generated by Django 5.2.8 on 2025-11-18 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "units_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How many units were used (e.g., 1 can, 0.5 liter, 3 pieces)",
                        max_digits=10,
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="e.g., 'Picked up at shop', 'Delivered to home'",
                    ),
                ),
            ],
            options={
                "db_table": "card_usage",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="PrepaidCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_units", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "used_units",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "remaining_units",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("exhausted", "Exhausted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("exhausted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "prepaid_cards",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="PrepaidCardOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Starter Pack', '30-Can Card', 'Monthly Card'",
                        max_length=100,
                    ),
                ),
                (
                    "total_units",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total units in card (e.g., 30 cans, 30 liters, 50 pieces)",
                        max_digits=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for the card",
                        max_digits=10,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated: price / total_units",
                        max_digits=10,
                    ),
                ),
                (
                    "savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Savings compared to base price",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in listing (lower = shown first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prepaid_card_options",
                "ordering": ["service", "display_order", "total_units"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit for one-time orders (e.g., ₹10 per can)",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., can, liter, piece, kg", max_length=50
                    ),
                ),
                (
                    "quantity_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Example: [{"label": "250ml", "value": 0.25, "price": 15}, {"label": "1 Liter", "value": 1, "price": 60}]',
                    ),
                ),
                ("minimum_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("has_stock_tracking", models.BooleanField(default=True)),
                ("current_stock", models.IntegerField(default=0)),
                ("business_hours_start", models.TimeField(default="06:00:00")),
                ("business_hours_end", models.TimeField(default="22:00:00")),
                (
                    "operating_days",
                    models.JSONField(
                        default=list,
                        help_text='["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]',
                    ),
                ),
                (
                    "supports_immediate_delivery",
                    models.BooleanField(
                        default=True,
                        help_text="Can customers order for immediate delivery?",
                    ),
                ),
                (
                    "immediate_delivery_time",
                    models.IntegerField(
                        default=120,
                        help_text="Expected delivery time in minutes (e.g., 120 = 2 hours)",
                    ),
                ),
                (
                    "supports_prepaid_cards",
                    models.BooleanField(
                        default=True,
                        help_text="Does this service support prepaid cards?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "db_table": "service_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("business_address", models.TextField()),
                ("business_phone", models.CharField(max_length=15)),
                ("business_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_providers",
            },
        ),
    ]
