# Generated by Django 5.2.8 on 2025-11-16 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "db_table": "service_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("business_address", models.TextField()),
                ("business_phone", models.CharField(max_length=15)),
                ("business_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_providers",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("self_pickup", "Self Pickup"),
                            ("auto_delivery", "Auto Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_units", models.IntegerField()),
                ("used_units", models.IntegerField(default=0)),
                ("remaining_units", models.IntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                (
                    "delivery_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days for auto-delivery: ['monday', 'wednesday', 'friday']",
                    ),
                ),
                (
                    "units_per_delivery",
                    models.IntegerField(
                        default=1, help_text="Units to deliver each time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Starter Pack', 'Value Pack', 'Family Pack'",
                        max_length=100,
                    ),
                ),
                ("units", models.IntegerField(help_text="Total units in package")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Savings compared to base price",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in listing (lower = shown first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_packages",
                "ordering": ["display_order", "units"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("units_used", models.IntegerField(default=1)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[("pickup", "Self Pickup"), ("delivered", "Delivered")],
                        max_length=20,
                    ),
                ),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subscription_usage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("per_unit", "Per Unit"),
                            ("subscription", "Subscription Only"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., bottle, kg, litre", max_length=50
                    ),
                ),
                ("minimum_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("has_stock_tracking", models.BooleanField(default=True)),
                ("current_stock", models.IntegerField(default=0)),
                ("business_hours_start", models.TimeField(default="06:00:00")),
                ("business_hours_end", models.TimeField(default="22:00:00")),
                (
                    "operating_days",
                    models.JSONField(
                        default=list,
                        help_text="Days service is available: ['monday', 'tuesday', ...]",
                    ),
                ),
                ("supports_immediate_delivery", models.BooleanField(default=True)),
                (
                    "immediate_delivery_time",
                    models.IntegerField(
                        default=120,
                        help_text="Minutes for immediate delivery (e.g., 120 = within 2 hours)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "services",
            },
        ),
    ]
