# Generated by Django 5.2.8 on 2025-11-18 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cardusage",
            name="marked_by",
            field=models.ForeignKey(
                help_text="Vendor who marked the card",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_card_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prepaidcard",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prepaid_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardusage",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_history",
                to="services.prepaidcard",
            ),
        ),
        migrations.AddField(
            model_name="prepaidcard",
            name="card_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_cards",
                to="services.prepaidcardoption",
            ),
        ),
        migrations.AddField(
            model_name="prepaidcardoption",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prepaid_card_options",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.serviceprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="cardusage",
            index=models.Index(
                fields=["card", "used_at"], name="card_usage_card_id_65d319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prepaidcard",
            index=models.Index(
                fields=["customer", "status"], name="prepaid_car_custome_628343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prepaidcard",
            index=models.Index(
                fields=["card_option"], name="prepaid_car_card_op_6b5e27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prepaidcard",
            index=models.Index(
                fields=["purchased_at"], name="prepaid_car_purchas_040ce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prepaidcardoption",
            index=models.Index(
                fields=["service", "is_active"], name="prepaid_car_service_577d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprovider",
            index=models.Index(fields=["status"], name="service_pro_status_a75042_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceprovider",
            index=models.Index(
                fields=["created_at"], name="service_pro_created_f0ae23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["provider", "is_active"], name="services_provide_c85dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "is_available"], name="services_categor_35f305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["created_at"], name="services_created_22da02_idx"
            ),
        ),
    ]
