# Generated by Django 5.2.8 on 2025-11-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.serviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_packages",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="services.subscriptionpackage",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionusage",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionusage",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_history",
                to="services.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprovider",
            index=models.Index(fields=["status"], name="service_pro_status_a75042_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceprovider",
            index=models.Index(
                fields=["created_at"], name="service_pro_created_f0ae23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["provider", "is_active"], name="services_provide_c85dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "is_available"], name="services_categor_35f305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["created_at"], name="services_created_22da02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpackage",
            index=models.Index(
                fields=["service", "is_active"], name="subscriptio_service_036e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["customer", "status"], name="subscriptio_custome_34b933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["package"], name="subscriptio_package_99a4ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["created_at"], name="subscriptio_created_ecfb9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionusage",
            index=models.Index(
                fields=["subscription", "created_at"],
                name="subscriptio_subscri_37d95a_idx",
            ),
        ),
    ]
